### ISSUE TITLE
Occasional Trigger_Error() on shopping cart page

### ISSUE THREAD

**Issue by JeffMash** [lat9/favorites_wishlist_support#3]
Using zc 1.5.8a and Favorites 6.0.0.

I am seeing the occasional PHP warning in the ZC logs:

```
[30-Apr-2023 12:55:42 America/Los_Angeles] Request URI: /store/shopping_cart.html, IP address: 77.137.77.127, Language id 1
#1  trigger_error() called at [/home/mydomain/public_html/store/includes/templates/bootstrap/templates/tpl_shopping_cart_default.php:357]
#2  require(/home/mydomain/public_html/store/includes/templates/bootstrap/templates/tpl_shopping_cart_default.php) called at [/home/mydomain/public_html/store/includes/templates/bootstrap/common/tpl_main_page.php:257]
#3  require(/home/mydomain/public_html/store/includes/templates/bootstrap/common/tpl_main_page.php) called at [/home/mydomain/public_html/store/index.php:94]
--> PHP Warning: includes/templates/bootstrap/templates/tpl_modules_favorites_shopping_cart.php in /home/mydomain/public_html/store/includes/templates/bootstrap/templates/tpl_shopping_cart_default.php on line 357.
```

I haven't been able to reproduce it yet but this seems to happen randomly.  Out of thousands of daily sessions, I see three so far today (one at 9:47am, one at 12:55pm, and one at 5:34pm).   So it's a few hours apart but still a head-scratcher as to why it's happening.

**Comment by lat9** [comment]
What's the code on/around line 357 of your `/includes/templates/bootstrap/templates/tpl_shopping_cart_default.php`?  I'm not seeing any `trigger_error` calls in my integration's file-system.  For that matter, the Bootstrap 3.5.3. version of that file only has 280 lines.

**Comment by JeffMash** [comment]
I do have a bunch of additions to my shopping cart page (mainly to display shipping times and free shipping incentives), so that's why my file is much longer than the stock file.

Here is the code I currently have between lines 350 to 361:

```
<?php
    // -----
    // Enable extra content to be included, via additional header_php_*.php files present
    // in /includes/modules/pages/shopping_cart.
    //
    if (!empty($extra_content_shopping_cart) && is_array($extra_content_shopping_cart)) {
        foreach ($extra_content_shopping_cart as $extra_content) {
            trigger_error($extra_content, E_USER_WARNING);
            require $extra_content;
        }
    }
?>
```

**Comment by lat9** [comment]
That `trigger_error` was in a pre-release (or v3.5.2) of the Bootstrap Template v3.5.3 and can be safely removed (it's removed from v3.5.3 of the template).

**Comment by JeffMash** [comment]
Thanks  Cindy!  Glad to hear it's not  detrimental part of the template.   I'll remove it.   Funny thing is that I am running 3.5.3 but I must have not caught that removal of code when doing my merges between versions.

**Comment by lat9** [comment]
It was a 'late removal' from v3.5.3 of the template during my release-testing for `favorites_wishlist`: https://github.com/lat9/ZCA-Bootstrap-Template/issues/232
